name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 10
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: npm ci
    - run: npm test
  lint-js:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 10
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: npm ci
    - run: npm run lint:js
  lint-css:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 10
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: npm ci
    - run: npm run lint:css
  generator:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 10
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: npm i -g .
    - run: npx --no-install @ubio/sdk --name application-build --domain hotel-booking
